# 프로그램 설치 파일을 만드는, 최종적으로 검증된 완벽한 설명서입니다.
name: Create App Installers

# 'main' 브랜치에 파일이 업로드될 때마다 자동으로 공장을 돌립니다.
on:
  push:
    branches: [ "main" ]

# '만들기' 작업에 대한 상세 설명
jobs:
  build:
    # 윈도우와 맥, 두 종류의 컴퓨터에서 동시에 작업을 실행합니다.
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    # 실제 작업 단계
    steps:
      # 1단계: 인터넷에서 최신 설계도를 가져옵니다. (최신 부품 v4 사용)
      - name: 1. Check out project files
        uses: actions/checkout@v4

      # 2단계: 최신 Node.js 작업대를 설치합니다. (최신 부품 v4 사용)
      - name: 2. Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3단계: 필요한 모든 부품들을 조립합니다.
      - name: 3. Install all dependencies
        run: npm install

      # 4단계: 부품과 설계도로 실제 프로그램을 만듭니다.
      - name: 4. Create app packages
        run: npm run pack

      # 5단계: 완성된 프로그램을 다운로드받을 수 있게 포장해서 올려놓습니다. (가장 중요한 최신 부품 v4 사용)
      - name: 5. Upload the finished apps
        uses: actions/upload-artifact@v4
        with:
          name: Faperlink-App-${{ matrix.os }}
          path: dist
